### ISSUE TITLE
Strange behaviour in split screen mode

### ISSUE THREAD

**Issue by SurajDadral** [Sudhanshu-Dubey14/ExamShield#3]
Although it says this app doesn't support split screen mode, but on Redmi 7 android 9, I can make app fit split screen, if I split screen before clicking start exam. Not afterwards.
And in split screen, I clicked on one button of another app.
Then I reached home screen of my phone and my split screen is now shown in notification bar, but can't recover/reach app again.
So, I need to restart phone.

**Comment by Sudhanshu-Dubey14** [comment]
Resolved in commit c04c94e5a5a606a7df3a2033b413d69881c21113.
Hence I will close this issue.
